apiVersion: v1
kind: Service
metadata:
  name: {{ include "wire.fullname" . }}-headless
  labels:
    app: {{ include "wire.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "wire.fullname" . }}
  ports:
    - name: epmd
      port: 4369