{{- if .Values.git.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env }}-git-repo-config
  namespace: {{ .Values.global.namespace | default "argocd" }}
  labels:
    # This label tells ArgoCD to treat this secret as a repository connection
    argocd.argoproj.io/secret-type: repository
stringData:
  name: {{ .Values.env }}-manifest-repo
  url: {{ .Values.global.repoURL | quote }}
  # CHANGE: Type is now 'git'
  type: git
  # ADD: Credentials if your Gitea repo ever becomes private
  username: {{ .Values.git.username | default "admin" | quote }}
  password: {{ .Values.git.password | default "placeholder" | quote }}
{{- end }}