# values.yaml
image:
  repository: ghcr.io/open-webui/open-webui
  tag: v0.8.12
  pullPolicy: IfNotPresent

replicaCount: 1
fullnameOverride: "open-webui"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ollama:
  baseUrl: "http://ollama-internal.ollama.svc.cluster.local:11434"

openai:
  # baseUrl: "http://don-erleone.don-erleone.svc.cluster.local:8080/v1"
  baseUrl: ""

# Additional environment variables to inject into the container (Key-Value pairs)
env: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi

resources:
  limits:
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "512Mi"
