cabal-version:      3.12
name:               agent-brain
version:            0.1.0.0
synopsis:           Servant API for Agent Orchestration Brain
license:            Apache-2.0
license-file:       LICENSE
author:             PudgyPigeon
maintainer:         tommynam1994@gmail.com
category:           Model Context Protocol
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: 
            -Wall 
            -Wcompat 
            -Wincomplete-record-updates 
            -Wincomplete-uni-patterns 
            -Wredundant-constraints

library
    import:           warnings
    -- Generates separate sections for each function
    ghc-options:      
        -fsplit-sections  
    exposed-modules:  
        Server,
        -- Health,
        -- Types,
        -- Config
    build-depends:    
    build-depends:    
        base >=4.21.0.0,
        aeson,
        servant,
        servant-server,
        text,
        bytestring,
        wai,
        warp,
        http-types,
        optparse-applicative >= 0.18.1.0
    hs-source-dirs:   src
    default-language: GHC2024

executable agent-brain
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base >=4.21.0.0,
        agent-brain
    hs-source-dirs:   app
    default-language: GHC2024
    ghc-options: 
            -threaded 
            -rtsopts 
            "-with-rtsopts=-N"
            -- High level optimization
            -O2              
            -- Similar to Rust's dead-code elimination
            -fsplit-sections 
            -- Tells the linker to strip all symbols
            -optl-Wl,--strip-all 
            -optl-Wl,--gc-sections

test-suite agent-brain-test
    import:           warnings
    default-language: GHC2024
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base >=4.21.0.0,
        sydtest,           
        agent-brain