apiVersion: v2
name: envoy-gateway
description: Envoy Gateway API Controller (wraps upstream chart)
type: application
version: 0.1.0
dependencies:
  - name: gateway
    version: "v1.0.1"
    repository: "oci://docker.io/envoyproxy/gateway-helm"
