{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-mcp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-mcp.labels" . | nindent 4 }}
{{- end }}
